# contenedores
services:
  nodecito:
    # donde se encuentra el Dockerfile
    build: .
    ports:
    # puertos <anfitrion>:<contenedor>
      - "3000:3000"
    # enlaces entre contenedores por nombre
    links:
      - monguito
  monguito:
    image: mongo
    # image: dannyben/alpine-mongo:latest
    ports:
      - "27017:27017"
    # variables de entorno
    environment:
    - MONGO_INITDB_ROOT_USERNAME=cesar
    - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      # donde se almacenarán los datos persistentes de cada contenedor por defecto
      - mongo-data:/data/db
      # ejemplo de otras db:
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
 mongo-data: